<script setup lang="ts">
// definePageMeta({
//   middleware: ["auth"],
// });

const dmpStore = useState('dmp-data')

const dmp = computed(() => dmpStore.value)
if (!dmp.value) {
  navigateTo('/app/dmp')
}
const items = ref([
  {
    date: 'Step 1',
    title: 'Project Details',
    description: 'Completed',
    icon: 'line-md:confirm-circle',
    ui: {
      description: 'text-blue-400',
    },
  },
  {
    date: 'Step 2',
    title: 'Draft Review',
    description: 'In Progress',
    icon: 'line-md:confirm-circle-twotone-to-circle-twotone-transition',
    ui: {
      description: 'text-blue-400',
    },
  },
  {
    date: 'Step 3',
    title: 'Download',
    description: 'Pending',
    icon: 'line-md:confirm-circle-twotone-to-circle-transition'
  }
])
const open = ref(true)

defineShortcuts({
  o: () => open.value = !open.value
})

const showBackConfirm = ref(false)

function confirmBack() {
  // Clear DMP data (optional, since it will be lost)
  dmpStore.value = null
  // Navigate back
  navigateTo('/app/dmp')
}
</script>

<template>
<div class="relative">
  <div class="absolute inset-x-0 top-0 h-40 bg-gradient-to-b from-blue-300 to-white dark:from-blue-800 dark:to-transparent -z-10"></div>

  <div class="mx-auto flex w-full max-w-screen-xl flex-col gap-6 px-6 pt-6">

  <div class="flex items-center justify-between mb-6 mt-6">
  <h1 class="text-4xl font-bold text-blue-500 dark:text-blue-300">
    Test DMP Chef
  </h1>

  <UButton
    @click="navigateTo('/app/download')"
    color="neutral"
    variant="outline"
    icon="i-lucide-file-text"
    class="flex items-center gap-3 px-6 py-3"
  >
    Download DMP
  </UButton>
</div>
  <div class="p-4 rounded-lg bg-amber-50 dark:bg-amber-900 border border-amber-200 dark:border-amber-800 flex items-start space-x-3">
    <UIcon name="i-heroicons-exclamation-triangle-20-solid" class="w-5 h-5 flex-shrink-0 text-amber-500 dark:text-amber-300" />
    <div>
      <h3 class="text-sm font-medium text-amber-800 dark:text-amber-100">
        This page is meant only for testing and validating the DMP Chef Python pipeline. 
    Ultimately, the DMP Chef pipeline will be integrated in DMPTool.org to provide researchers with a 
    familiar and convenient user interface that does not require any coding knowledge.
    </h3>
    </div>
  </div>

  <UTimeline orientation="horizontal" :default-value="1.5" :items="items" size="sm" class="w-full mb-6 ml-30" />
  <div class="bg-gray-50 border border-gray-200 rounded-lg p-6 dark:bg-gray-800 dark:border-gray-700">
    <span class="inline-block bg-indigo-600 text-white text-xs font-bold px-2 py-1 rounded mb-3 uppercase tracking-wide dark:bg-indigo-500">
      Action Required
    </span>
    <p class="text-lg text-gray-800 font-medium dark:text-gray-100 mb-1">
      Read the generated DMP below and edit it as needed.
    </p>
    <p class="text-base">This plan is based on the "NIH-Default DMSP" 
      <a
        href="https://www.google.com/url?q=https://dmptool.org/public_templates?page%3D1%26search%3Dnih-default&sa=D&source=docs&ust=1763968091481647&usg=AOvVaw36cUJD07--3Vwk3mxOgnJY"
        target="_blank"
        rel="noopener noreferrer"
        class="text-blue-400 underline"
      >
      template</a> provided by National Institutes of Health (nih.gov) 
    </p>
  </div>

  <div class="p-4 rounded-lg bg-amber-50 dark:bg-amber-900 border border-amber-200 dark:border-amber-800 flex items-start space-x-3">
    <UIcon name="i-heroicons-exclamation-triangle-20-solid" class="w-5 h-5 flex-shrink-0 text-amber-500 dark:text-amber-300" />
    <div>
      <h3 class="text-sm font-medium text-amber-800 dark:text-amber-100">
        Remember that this draft is generated by a large language model (LLM) and may not be completely accurate. Please use your own judgment and verify important information.
      </h3>
    </div>
  </div>

  <div class="space-y-6">

    <!-- ELEMENT 1: Data Type -->
    <UCollapsible 
      v-model:open="open"
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 1: Data Type"
        icon="i-heroicons-document-text"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          // Apply rotation logic directly to the chevron icon class
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-8 border-t border-gray-100 dark:border-gray-800">

          <!-- Main Instructions (Styled as a pull-quote) -->
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            Briefly describe the scientific data to be managed, preserved, and shared.
          </p>

          <!-- 1A -->
          <div class="space-y-2">
            <div class="flex items-center gap-3">
              <UBadge variant="subtle" size="md" class="font-bold rounded-md">1A</UBadge>
              <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                Types and amount of scientific data expected to be generated in the project
              </h3>
            </div>
            <p class="text-sm text-gray-500 ml-[40px]">
              Summarize the types and estimated amount of scientific data expected to be generated in the project.
            </p>

            <UTextarea
              :rows="8"
              class="w-full"
              v-model="dmp['Element 1: Data Type']['1'].description"
              autoresize
            />
          </div>

          <!-- 1B -->
          <div class="space-y-2">
            <div class="flex items-center gap-3">
              <UBadge variant="subtle" size="md" class="font-bold rounded-md">1B</UBadge>
              <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                Scientific data that will be preserved and shared, and the rationale for doing so
              </h3>
            </div>
            <p class="text-sm text-gray-500 ml-[40px]">
              Describe which scientific data from the project will be preserved and shared and provide the rationale for this decision.
            </p>

            <UTextarea
              :rows="8"
              class="w-full"
              v-model="dmp['Element 1: Data Type']['2'].description"
              autoresize
            />
          </div>

          <!-- 1C -->
          <div class="space-y-2">
            <div class="flex items-center gap-3">
              <UBadge variant="subtle" size="md" class="font-bold rounded-md">1C</UBadge>
              <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                Metadata, other relevant data, and associated documentation
              </h3>
            </div>
            <p class="text-sm text-gray-500 ml-[40px]">
              Briefly list the metadata, other relevant data, and any associated documentation (e.g., study protocols and data collection instruments) 
              that will be made accessible to facilitate interpretation of the scientific data.
            </p>

            <UTextarea
              :rows="8"
              class="w-full"
              v-model="dmp['Element 1: Data Type']['3'].description"
              autoresize
            />
          </div>
        </div>
      </template>
    </UCollapsible>

    <!-- ELEMENT 2: Related Tools, Software and/or Code -->
    <UCollapsible 
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 2: Related Tools, Software and/or Code"
        icon="i-lucide-code"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-4 border-t border-gray-100 dark:border-gray-800">
          
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            State whether specialized tools, software, and/or code are needed to access or 
            manipulate shared scientific data, and if so, provide the name(s) of the needed 
            tool(s) and software and specify how they can be accessed.
          </p>

          <UTextarea
            :rows="8"
            class="w-full"
            v-model="dmp['Element 2: Related Tools, Software and/or Code'].description"
            autoresize
          />
        </div>
      </template>
    </UCollapsible>

    <!-- ELEMENT 3: Standards -->
    <UCollapsible 
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 3: Standards"
        icon="i-lucide-check-circle"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-4 border-t border-gray-100 dark:border-gray-800">
          
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            State what common data standards will be applied to the scientific data and associated 
            metadata to enable interoperability of datasets and resources and provide the name(s) 
            of the data standards that will be applied and describe how these data standards will 
            be applied to the scientific data generated by the research proposed in this project. 
            If applicable, indicate that no consensus standards exist.
          </p>

          <UTextarea
            :rows="8"
            class="w-full"
            v-model="dmp['Element 3: Standards'].description"
            autoresize
          />
        </div>
      </template>
    </UCollapsible>

    <!-- ELEMENT 4: Data Preservation, Access, and Associated Timelines -->
    <UCollapsible 
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 4: Data Preservation, Access, and Associated Timelines"
        icon="i-lucide-cloud"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-8 border-t border-gray-100 dark:border-gray-800">
          
          <!-- Main Instructions (Styled as a pull-quote) -->
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            There are various ways in which to disseminate, preserve, and make scientific data 
            discoverable. In this section, you should describe where and when the scientific 
            data associated with your research will be made available. The primary way to satisfy 
            this requirement is to put your scientific data into a repository, which will support 
            preservation of that data and provide long term access. In some cases, a repository may 
            be specified by the funding Institute or Center; if a repository is not specified, then 
            you have discretion in selecting the repository for your scientific data. When identifying 
            a repository, consider how your scientific data will be made discoverable through the platform. 
            For example, the repository’s ability to provide persistent identifiers (e.g., DOIs, handles, ARKs) 
            for your scientific data is a good starting point to ensure consistent access. If there are restrictions 
            as to the manner or length of time in which the scientific data can be preserved and/or accessed, 
            be clear as to what those restrictions are in this section.
          </p>

          <div v-if="dmp['Element 4: Data Preservation, Access, and Associated Timelines']" class="space-y-8">
            
            <!-- 4A -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">4A</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  Repository where scientific data and metadata will be archived
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                Provide the name of the repository(ies) where scientific data and metadata arising 
                from the project will be archived.
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 4: Data Preservation, Access, and Associated Timelines']['1'].description"
                autoresize
              />
            </div>

            <!-- 4B -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">4B</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  How scientific data will be findable and identifiable
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                Describe how the scientific data will be findable and identifiable, 
                i.e., via a persistent unique identifier or other standard indexing tools.
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 4: Data Preservation, Access, and Associated Timelines']['2'].description"
                autoresize
              />
            </div>

            <!-- 4C -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">4C</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  When and how long the scientific data will be made available
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                Describe when the scientific data will be made available to other users 
                (i.e., no later than time of an associated publication or end of the performance 
                period, whichever comes first) and for how long data will be available.
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 4: Data Preservation, Access, and Associated Timelines']['3'].description"
                autoresize
              />
            </div>
          </div>
        </div>
      </template>
    </UCollapsible>

    <!-- ELEMENT 5: Access, Distribution, or Reuse Considerations -->
    <UCollapsible 
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 5: Access, Distribution, or Reuse Considerations"
        icon="i-lucide-lock"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-8 border-t border-gray-100 dark:border-gray-800">
          
          <!-- Main Instructions (Styled as a pull-quote) -->
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            NIH expects that in drafting Plans, researchers maximize the appropriate sharing of 
            scientific data generated from NIH-funded or conducted research, consistent with 
            privacy, security, informed consent, and proprietary issues.
          </p>

          <div v-if="dmp['Element 5: Access, Distribution, or Reuse Considerations']" class="space-y-8">
            
            <!-- 5A -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">5A</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  Factors affecting subsequent access, distribution, or reuse of scientific data
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                Describe and justify any applicable factors or data use limitations affecting subsequent access, 
                distribution, or reuse of scientific data related to informed consent, privacy and 
                confidentiality protections, and any other considerations that may limit the extent of data sharing.
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 5: Access, Distribution, or Reuse Considerations']['1'].description"
                autoresize
              />
            </div>

            <!-- 5B -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">5B</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  Whether access to scientific data will be controlled
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                State whether access to the scientific data will be controlled (i.e., made available by a data 
                repository only after approval).
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 5: Access, Distribution, or Reuse Considerations']['2'].description"
                autoresize
              />
            </div>

            <!-- 5C -->
            <div class="space-y-2">
              <div class="flex items-center gap-3">
                <UBadge variant="subtle" size="md" class="font-bold rounded-md">5C</UBadge>
                <h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
                  Protections for privacy, rights, and confidentiality of human research participants
                </h3>
              </div>
              <p class="text-sm text-gray-500 ml-[40px]">
                if generating scientific data derived from humans, describe how the privacy, 
                rights, and confidentiality of human research participants will be protected 
                (e.g., through de-identification, Certificates of Confidentiality, and other protective measures).
              </p>

              <UTextarea
                :rows="8"
                class="w-full"
                v-model="dmp['Element 5: Access, Distribution, or Reuse Considerations']['3'].description"
                autoresize
              />
            </div>
          </div>
        </div>
      </template>
    </UCollapsible>

    <!-- ELEMENT 6: Oversight of Data Management and Sharing -->
    <UCollapsible 
      class="border border-gray-200 dark:border-gray-800 rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-900"
    >
      <UButton
        class="group py-4 px-6 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        color="neutral"
        variant="ghost"
        block
        label="Element 6: Oversight of Data Management and Sharing"
        icon="i-lucide-eye"
        trailing-icon="i-lucide-chevron-down"
        :ui="{
          base: 'flex justify-between items-center w-full text-lg font-semibold',
          trailingIcon: 'w-5 h-5 text-gray-400 transition-transform duration-200 group-data-[state=open]:rotate-180'
        }"
      />

      <template #content>
        <div class="p-6 space-y-4 border-t border-gray-100 dark:border-gray-800">
          
          <p class="text-gray-500 dark:text-gray-400 italic border-l-2 border-blue-500 pl-4">
            Describe how compliance with this Plan will be monitored and managed, frequency of oversight, 
            and by whom at your institution (e.g., titles, roles).
          </p>

          <div v-if="dmp['Element 6: Oversight of Data Management and Sharing']">
            <UTextarea
              :rows="8"
              class="w-full"
              v-model="dmp['Element 6: Oversight of Data Management and Sharing'].description"
              autoresize
            />
          </div>
        </div>
      </template>
    </UCollapsible>
  </div>


    <div class="flex justify-between pt-4">
  <UModal
    v-model:open="showBackConfirm"
    :prevent-close="true"
    title="Confirm Navigation"
  >
    <!-- Trigger button inside modal as per Nuxt pattern -->
    <UButton
      color="primary"
      size="xl"
      class="w-25"
      icon="ooui:arrow-next-rtl"
    >
      Back
    </UButton>

    <template #body>
      <p class="text-gray-700 dark:text-gray-200">
        Are you sure you want to go back? The generated DMP will be lost.
      </p>
    </template>

    <template #footer="{ close }">
      <div class="flex justify-end gap-60 py-6"> <!-- taller footer -->
        <!-- Cancel calls the close function provided by the slot -->
        <UButton
          label="Cancel"
          color="primary"
          variant="outline"
          size="xl"
          @click="close()"
        />
        <UButton
          label="Yes, go back"
          color="success"
          size="xl"
          @click="confirmBack"
        />
      </div>
    </template>
  </UModal>

      <UButton 
        color="primary"
        size="xl"
        class="w-25"
        trailing-icon="ooui:arrow-next-ltr"
        to="/app/download"
      >
        Next
      </UButton>
    </div>

    <SkyBg />
  </div>
</div>
</template>

